version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: wizmap_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/dist:/app/dist
    env_file:
      - ./frontend/.env.local

  backend:
    build:
      context: ./backend
    container_name: wizmap_backend
    ports:
      - "8000:8000"  # 내부 포트 8000을 외부 포트 8000에 매핑
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    container_name: wizmap
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend